version: '3'

services:
  app:
    image: 'gy-mall-backend:0.1'
    restart: always
    volumes:
      - './gymall/.env:/app/gy-mall-backend/gymall/.env:ro'
      - './logs:/app/gy-mall-backend/gymall/logs'
      - './media:/app/gy-mall-backend/gymall/media'
      - './static:/app/gy-mall-backend/gymall/static'
    ports:
      - '8000:8000'

  db:
    image: 'mysql:8'
    command:
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    ports:
      - '127.0.0.1:13306:3306'
    volumes:
      - './mysql/data:/var/lib/mysql'

