version: '3'

services:
  app:
    image: 'ccr.ccs.tencentyun.com/aweffr-main/gy-mall-backend:0.3'
    restart: always
    volumes:
      - './gymall/.env:/app/gy-mall-backend/gymall/.env:ro'
      - './logs:/app/gy-mall-backend/logs'
      - './media:/app/gy-mall-backend/media'
      - './static:/app/gy-mall-backend/static'
    ports:
      - '8000:8000'


