# Generated by Django 3.2.11 on 2022-02-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='express_limit',
            field=models.IntegerField(default=0, verbose_name='起送运费'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='express_price',
            field=models.IntegerField(default=0, verbose_name='基础运费'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
