# Generated by Django 3.2.11 on 2022-02-10 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mall.models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20220208_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-create_at',), 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mall.merchant', verbose_name='商户'),
        ),
        migrations.CreateModel(
            name='OrderCollection',
            fields=[
                ('id', models.CharField(default=mall.models.get_order_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('creating', '创建中'), ('waiting_to_pay', '待支付'), ('paid_succeed', '支付成功'), ('unpaid_closed', '未支付关闭'), ('sending', '快递发送中'), ('finished', '已完成')], max_length=191)),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='订单总价')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_collections', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='mall.ordercollection', verbose_name='订单集合'),
        ),
    ]
