# Generated by Django 3.2.11 on 2022-02-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20220210_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpressaddress',
            name='city',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='城市'),
        ),
    ]
