# Generated by Django 3.2.11 on 2022-02-13 05:57

from django.db import migrations, models
from django.db.models import Q


def init_keyword(apps, schema_editor):
    Product = apps.get_model("mall", "Product")
    Merchant = apps.get_model("mall", "Merchant")
    db_alias = schema_editor.connection.alias
    for product in Product.objects.using(db_alias).filter(Q(pinyin_keywords__isnull=True) | Q(search_keywords__isnull=True)):
        product.init_keywords()
        product.save(init_keywords_called=True)
    for merchant in Merchant.objects.using(db_alias).filter(Q(pinyin_keywords__isnull=True) | Q(search_keywords__isnull=True)):
        merchant.init_keywords()
        merchant.save(init_keywords_called=True)


class Migration(migrations.Migration):
    dependencies = [
        ('mall', '0004_userexpressaddress_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='pinyin_keywords',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='拼音关键字'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='search_keywords',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='搜索关键字'),
        ),
        migrations.AddField(
            model_name='product',
            name='pinyin_keywords',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='拼音关键字'),
        ),
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='搜索关键字'),
        ),
        migrations.RunPython(init_keyword)
    ]
